# Ubuntu default .bashrc file
source ~/..bashrcData/.default

# -------------------------- Here is my customized configures ----------------------------------------

# env variables setting(all export command)
source ~/..bashrcData/env

# common system command
source ~/..bashrcData/sys_command

# some higher abstract function
source ~/..bashrcData/func

# This is ysyx PATH generated by ysyx-workbench/init.sh
export NPC_HOME=/home/icer/ysyx/ysyx-workbench/npc
